language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed oanhtp/udagram-api-feed:v9
  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user oanhtp/udagram-api-user:v9
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-reverseproxy oanhtp/udagram-reverseproxy:v9
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend oanhtp/udagram-frontend:v9

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push oanhtp/udagram-reverseproxy:v9
  - docker push oanhtp/udagram-api-feed:v9
  - docker push oanhtp/udagram-api-user:v9
  - docker push oanhtp/udagram-frontend:v9
