apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
spec:
  selector:
    matchLabels:
      run: reverseproxy
  replicas: 2
  template:
    metadata:
      labels:
        run: reverseproxy
    spec:
      containers:
        - image: oanhtp/udagram-reverseproxy:v14
          name: reverseproxy
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
      restartPolicy: Always
